// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// UltraHonk verifier interface generated by `bb contract`.
interface IHonkVerifier {
    function verify(
        bytes calldata proof,
        bytes32[] calldata publicInputs
    ) external view returns (bool);
}

// pm_deposit.nr: oldRoot, assetDomain, amount, noteCommitment, amountCommitment, newRoot
interface IDepositVerifier is IHonkVerifier {}

// pm_withdraw.nr (10 inputs): root, nullifierHash, sharesPublic, sharePrice, amount,
// vaultId, recipient, relayer, fee, extDataHash
interface IVaultSpendVerifier is IHonkVerifier {}

// pm_balance_proof.nr: oldRoot, assetDomain, requiredAmount, orderCommitment,
// noteNullifierHash, balanceProofDigest
interface IBalanceProofVerifier is IHonkVerifier {}

// pm_settlement.nr: oldRoot, nullifier, receiverCommitment, changeCommitment
interface ITransferSettlementVerifier is IHonkVerifier {}

// pm_claim.nr: oldRoot, destinationAddressField, marketId, outcome, amount,
// nullifier, claimAuthDigest
interface IMarketClaimVerifier is IHonkVerifier {}

// pm_yield_distribution.nr: old_root, epoch_yield, total_locked, claimed_yield,
// nullifier, new_note_commitment, new_root
interface IYieldDistributionVerifier is IHonkVerifier {}

// placeholder for tooling compatibility
interface IOrderCommitVerifier is IHonkVerifier {}
